name = "Zzo"
description = "Blog theme for Hugo with multiple skins."
homepage = "https://github.com/zzossig/hugo-theme-zzo.git"
license = "MIT"
licenselink = "https://github.com/zzossig/hugo-theme-zzo/blob/master/LICENSE.md"
tags = ["accessible", "multilingual", "responsive", "blog", "search", "simple", "light", "dark", "mobile", "gallery"]
features = ["accessible", "multilingual", "responsive", "grid", "sass", "search", "jsonfeed", "subtheme", "gallery"]
min_version = "0.58.0"

[author]
  name = "zzossig"
  homepage = "https://example.com/"